# Do not forget to change the version number stored in config/version.ads
#
VERSION = Cheddar-3.4

# Select either between 'Release' or 'Debug'
# Do not forget to change also Debug_Level in config/framework_config.ads
RELEASE_OR_DEBUG = Release


